ALTER TABLE users
ADD COLUMN IF NOT EXISTS auth_user_id UUID UNIQUE;

ALTER TABLE users
ALTER COLUMN password_hash DROP NOT NULL;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS preferred_contact_method TEXT;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(30);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS instagram_handle VARCHAR(100);
